/* eslint-disable */
// Rewrites the Next app's stylesheets so every rule applies only inside
// `.acpra`, the root element AcTransitStory renders.
//
// Gatsby puts every imported stylesheet on every page of the site, and the
// app's CSS was written for a page of its own: `:root` variables, `html,
// body` rules, bare element selectors. Scoped, none of it can reach another
// article. The Next app (nextjsvis) is the source of truth; rerun this after
// its CSS changes:
//
//   node src/visuals/ac-transit-visuals/scope-css.js <path-to-nextjsvis>
const fs = require('fs');
const path = require('path');
const postcss = require('postcss');

const ROOT = '.acpra';
const SOURCES = {
  'app/globals.css': 'styles/app.css',
  'components/story/story.css': 'styles/story.css',
  'components/methodology/methodology.css': 'styles/methodology.css',
};

function scopeSelector(selector) {
  const s = selector.trim();
  // The page-level selectors all become the root element itself.
  if (s === ':root' || s === 'html' || s === 'body') return ROOT;
  if (s === '*') return `${ROOT} *`;
  // `body:has(.x)` qualifies the root itself; `body .x` is a descendant.
  if (/^(html|body)[:.[]/.test(s)) return s.replace(/^(html|body)/, ROOT);
  if (/^(html|body)\s/.test(s)) return s.replace(/^(html|body)\s+/, `${ROOT} `);
  return `${ROOT} ${s}`;
}

const scope = () => ({
  postcssPlugin: 'scope',
  Rule(rule) {
    // Keyframe steps are not selectors.
    if (rule.parent?.type === 'atrule' && /keyframes$/.test(rule.parent.name)) return;
    if (rule.selector.startsWith(ROOT)) return;
    rule.selectors = [...new Set(rule.selectors.map(scopeSelector))];
  },
});
scope.postcss = true;

// The site's typography plugin and MUI baseline style bare h1, p, a, button
// and so on. The app was written against browser defaults, so inside the root
// those elements go back to them; the app's own rules outrank this one.
// Leaflet's panes and controls are left alone: its rules are single classes,
// the same weight as this one, and would lose or win by load order.
const RESET = `/* Generated by scope-css.js from the nextjsvis app's stylesheets.
   Do not edit by hand. */
${ROOT} :where(h1, h2, h3, h4, h5, h6, p, ul, ol, li, dl, dd, dt, a, button,
  input, select, textarea, label, table, thead, tbody, tr, th, td, figure,
  figcaption, blockquote, small, strong, b, em, i, code, pre, hr):where(:not(.leaflet-container *)) {
  all: revert;
}
`;

const source = process.argv[2];
if (!source) {
  console.error('usage: node scope-css.js <path-to-nextjsvis>');
  process.exit(1);
}
Object.entries(SOURCES).forEach(([from, to], index) => {
  const css = fs.readFileSync(path.join(source, from), 'utf8');
  const out = postcss([scope]).process(css, { from }).css;
  const target = path.join(__dirname, to);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, (index === 0 ? RESET : '/* Generated by scope-css.js. Do not edit by hand. */\n') + out);
  console.log(`${from} -> ${to}`);
});
