export const allData = [
  {
    Name: 'Shareef Abdur-Rahim',
    Sport: 'Basketball (M) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Nathan Adrian',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Nathan Adrian',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 1,
    Silver: 1,
    Medals: 2,
  },
  {
    Name: 'Nathan Adrian',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2016,
    Bronze: 2,
    Gold: 2,
    Silver: 0,
    Medals: 4,
  },
  {
    Name: 'George Ahlgren',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Par Arvidsson',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1980,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Peter Asch',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1972,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Kathleen Baker',
    Sport: 'Swimming (W)',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 1,
    Silver: 1,
    Medals: 2,
  },
  {
    Name: 'Begnt Baron',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1980,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Begnt Baron',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1984,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Sebastian Bea',
    Sport: 'Crew (M) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Matt Biondi',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Matt Biondi',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1988,
    Bronze: 1,
    Gold: 5,
    Silver: 1,
    Medals: 7,
  },
  {
    Name: 'Matt Biondi',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1992,
    Bronze: 0,
    Gold: 2,
    Silver: 1,
    Medals: 4,
  },
  {
    Name: 'James Blair',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Donald Blessing',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Rachel Bootsma',
    Sport: 'Swimming (W)',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Gillian Boxx',
    Sport: 'Softball',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'John M. Brinck',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'David Brown',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Lloyd Butler',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Erin Cafaro',
    Sport: 'Crew (W) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Erin Cafaro',
    Sport: 'Rowing (W)',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Herbert Caldwell',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Milorad Cavic',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Charles Chandler',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Brandi Chastain',
    Sport: 'Soccer (W) ',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Brandi Chastain',
    Sport: 'Soccer (W) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Pete Cipollone',
    Sport: 'Crew (M) ',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Bob Clark',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1936,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Natalie Coughlin',
    Sport: 'Swimming (W)',
    'Olympic Year': 2004,
    Bronze: 1,
    Gold: 2,
    Silver: 2,
    Medals: 5,
  },
  {
    Name: 'Natalie Coughlin',
    Sport: 'Swimming (W)',
    'Olympic Year': 2008,
    Bronze: 3,
    Gold: 1,
    Silver: 2,
    Medals: 6,
  },
  {
    Name: 'Natalie Coughlin',
    Sport: 'Swimming (W)',
    'Olympic Year': 2012,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Tammy Crow',
    Sport: 'Synch. Swimming',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ann Curtis Cuneo',
    Sport: 'Swimming (W)',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 2,
    Silver: 1,
    Medals: 3,
  },
  {
    Name: 'William Dally',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'George Davis',
    Sport: 'Rugby  ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Megan Dirkmaat',
    Sport: 'Crew (W) ',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'George Dixon',
    Sport: 'Rugby  ',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Peter Donlon',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Duje Draganja',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Dave Dunlap',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Phillip Durbrow',
    Sport: 'Crew (M) ',
    'Olympic Year': 1964,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ky Ebright',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ky Ebright',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ky Ebright',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Anthony Ervin',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 1,
    Silver: 1,
    Medals: 2,
  },
  {
    Name: 'Anthony Ervin',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 2,
    Silver: 0,
    Medals: 2,
  },
  {
    Name: 'Joy (Biefeld) Fawcett',
    Sport: 'Soccer (W) ',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Joy (Biefeld) Fawcett',
    Sport: 'Soccer (W) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Joy (Biefeld) Fawcett',
    Sport: 'Soccer (W) ',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'George Fish',
    Sport: 'Rugby  ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Scott Frandsen',
    Sport: 'Crew (M) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Missy Franklin',
    Sport: 'Swimming (W)',
    'Olympic Year': 2012,
    Bronze: 1,
    Gold: 4,
    Silver: 0,
    Medals: 5,
  },
  {
    Name: 'Missy Franklin',
    Sport: 'Swimming (W)',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Francis Frederick',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Vicky Galindo',
    Sport: 'Softball',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Sue Gossick',
    Sport: 'Diving',
    'Olympic Year': 1968,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ed "Mush" Graff',
    Sport: 'Rugby  ',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Norris Graham',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Michelle Granger',
    Sport: 'Softball',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Duncan Gregg',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Winslow Hall',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Brutus Hamilton',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Jessica Hardy',
    Sport: 'Swimming (W)',
    'Olympic Year': 2012,
    Bronze: 1,
    Gold: 1,
    Silver: 0,
    Medals: 2,
  },
  {
    Name: 'Jim Hardy',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Eddie Hart',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1972,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Mary Harvey',
    Sport: 'Soccer (W) ',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'John Hazeltine',
    Sport: 'Rugby  ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Mark Henderson',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Pelle Holmertz',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1980,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Chris Huffins',
    Sport: 'Track & Field (M)',
    'Olympic Year': 2000,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Darrall Imhoff',
    Sport: 'Basketball (M) ',
    'Olympic Year': 1960,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Sara Isakovic',
    Sport: 'Swimming (W)',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Scott Jaffe',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1992,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Helen Jameson',
    Sport: 'Swimming (W)',
    'Olympic Year': 1980,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Burton Jastram',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Courtney Johnson',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Sheryl Johnson',
    Sport: 'Field Hockey',
    'Olympic Year': 1984,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Jason Kidd',
    Sport: 'Basketball (M) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Jason Kidd',
    Sport: 'Basketball (M) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Bob Kiesel',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Leamon King',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1956,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Paul Kingsman',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1988,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Kara Kohler',
    Sport: 'Rowing (W)',
    'Olympic Year': 2012,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Laurel Korholz',
    Sport: 'Rowing (W)',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Oleg Kossiack',
    Sport: 'Gymnastics',
    'Olympic Year': 1996,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ludy Langer',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Thomas Lejdstrom',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1984,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Catilin Leverenz',
    Sport: 'Swimming (W)',
    'Olympic Year': 2012,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Harry Liversedge',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1920,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Carli Lloyd',
    Sport: 'Volleyball (W)',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Carli Lloyd',
    Sport: 'Volleyball (W)',
    'Olympic Year': 2016,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ericka Lorenz',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Ericka Lorenz',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2004,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Agneta Martensson',
    Sport: 'Swimming (W)',
    'Olympic Year': 1980,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Holly McPeak',
    Sport: 'Beach Volleyball',
    'Olympic Year': 2004,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Mary T. Meagher',
    Sport: 'Swimming (W)',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 3,
    Silver: 0,
    Medals: 3,
  },
  {
    Name: 'Mary T. Meagher',
    Sport: 'Swimming (W)',
    'Olympic Year': 1988,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Charles Meehan',
    Sport: 'Rugby  ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'George D. Mitchell',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1924,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Alex Morgan',
    Sport: 'Soccer (W) ',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Jonny Mosely',
    Sport: 'Freestyle Skiing',
    'Olympic Year': 1998,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Harold "Brick" Muller',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Ryan Murphy',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 3,
    Silver: 0,
    Medals: 3,
  },
  {
    Name: 'John Mykkanen',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Ed Nemir',
    Sport: 'Wrestling',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Pete Newell',
    Sport: 'Basketball (M) ',
    'Olympic Year': 1960,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Lowell North',
    Sport: 'Yachting',
    'Olympic Year': 1964,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Lowell North',
    Sport: 'Yachting',
    'Olympic Year': 1968,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: "Maureen O'Toole",
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Heather Petri',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Heather Petri',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2004,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Heather Petri',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Heather Petri',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Connie Carpenter Phinney',
    Sport: 'Cycling (W) ',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Marcy Place',
    Sport: 'Field Hockey',
    'Olympic Year': 1984,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Augustus Pope',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1920,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Josh Prenot',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Ralph Purchase',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Kevin Robertson',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Kevin Robertson',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1988,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Peter Rocca',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1976,
    Bronze: 0,
    Gold: 0,
    Silver: 2,
    Medals: 2,
  },
  {
    Name: 'Edwin Salisbury',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Aleksa Saponjic',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 2012,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Jill Savery',
    Sport: 'Synch. Swimming',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'George Schroth',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1924,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Tom Shields',
    Sport: 'Swimming (M) ',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Olivier Siegelaar',
    Sport: 'Rowing (M)',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Emily Silver',
    Sport: 'Swimming (W)',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Colby Slater',
    Sport: 'Rugby  ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Colby Slater',
    Sport: 'Rugby  ',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Graham Smith',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1976,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Guinn Smith',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Joe Smith',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1988,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Justus Smith',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'John Stack',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Martin F. Stalder',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Dave Steen',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1988,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Staciana Stitts',
    Sport: 'Swimming (W)',
    'Olympic Year': 2000,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Jon Svendsen',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Roser Taraggo',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Margot Thien',
    Sport: 'Synch. Swimming',
    'Olympic Year': 1996,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Joel Thomas',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1992,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'William Thompson',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Charles Tilden',
    Sport: 'Rugby  ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Harold Tower',
    Sport: 'Crew (M) ',
    'Olympic Year': 1932,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Nion Tucker',
    Sport: 'Bobsled',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ed Turkington',
    Sport: 'Rugby  ',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'David Turner',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Ian Turner',
    Sport: 'Crew (M) ',
    'Olympic Year': 1948,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Conny van Bentum',
    Sport: 'Swimming (W)',
    'Olympic Year': 1980,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Conny van Bentum',
    Sport: 'Swimming (W)',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Conny van Bentum',
    Sport: 'Swimming (W)',
    'Olympic Year': 1988,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Dana Vollmer',
    Sport: 'Swimming (W)',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Dana Vollmer',
    Sport: 'Swimming (W)',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 3,
    Silver: 0,
    Medals: 3,
  },
  {
    Name: 'Dana Vollmer',
    Sport: 'Swimming (W)',
    'Olympic Year': 2016,
    Bronze: 1,
    Gold: 1,
    Silver: 1,
    Medals: 3,
  },
  {
    Name: 'Abbey Weitzeil',
    Sport: 'Swimming (W)',
    'Olympic Year': 2016,
    Bronze: 0,
    Gold: 1,
    Silver: 1,
    Medals: 2,
  },
  {
    Name: 'Barry Weitzenberg',
    Sport: 'Water Polo (M) ',
    'Olympic Year': 1972,
    Bronze: 1,
    Gold: 0,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Tom Werner',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1992,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Jake Wetzel',
    Sport: 'Crew (M) ',
    'Olympic Year': 2004,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Jake Wetzel',
    Sport: 'Crew (M) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Hazel Hotchkiss Wightman',
    Sport: 'Tennis (W)',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 2,
    Silver: 0,
    Medals: 2,
  },
  {
    Name: 'Archie Williams',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1936,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Norris Williams',
    Sport: 'Tennis (M)',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Helen Wills',
    Sport: 'Tennis (W)',
    'Olympic Year': 1924,
    Bronze: 0,
    Gold: 2,
    Silver: 0,
    Medals: 2,
  },
  {
    Name: 'Dave Wilson',
    Sport: 'Swimming (M) ',
    'Olympic Year': 1984,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Elsie Windes',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2008,
    Bronze: 0,
    Gold: 0,
    Silver: 1,
    Medals: 1,
  },
  {
    Name: 'Elsie Windes',
    Sport: 'Water Polo (W) ',
    'Olympic Year': 2012,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'James Winston',
    Sport: 'Rugby   (M) ',
    'Olympic Year': 1920,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'James Workman',
    Sport: 'Crew (M) ',
    'Olympic Year': 1928,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
  {
    Name: 'Jack Yerman',
    Sport: 'Track & Field (M) ',
    'Olympic Year': 1960,
    Bronze: 0,
    Gold: 1,
    Silver: 0,
    Medals: 1,
  },
];
