const californiaCountiesData = {
  counties: [
    { name: 'Los Angeles', count: 83 },
    { name: 'Contra Costa', count: 65 },
    { name: 'Orange', count: 57 },
    { name: 'Alameda', count: 41 },
    { name: 'San Diego', count: 40 },
    { name: 'Santa Clara', count: 32 },
    { name: 'San Mateo', count: 25 },
    { name: 'Marin', count: 23 },
    { name: 'Riverside', count: 18 },
    { name: 'Sacramento', count: 16 },
    { name: 'Sonoma', count: 10 },
    { name: 'Ventura', count: 9 },
    { name: 'San Francisco', count: 9 },
    { name: 'Fresno', count: 7 },
    { name: 'San Bernardino', count: 7 },
    { name: 'Placer', count: 7 },
    { name: 'Solano', count: 6 },
    { name: 'Santa Barbara', count: 5 },
    { name: 'El Dorado', count: 5 },
    { name: 'Yolo', count: 4 },
    { name: 'Santa Cruz', count: 3 },
    { name: 'Stanislaus', count: 3 },
    { name: 'Monterey', count: 3 },
    { name: 'Merced', count: 2 },
    { name: 'Nevada', count: 2 },
    { name: 'San Luis Obispo', count: 2 },
    { name: 'San Joaquin', count: 2 },
    { name: 'Calaveras', count: 1 },
    { name: 'Glenn', count: 1 },
    { name: 'Napa', count: 1 },
    { name: 'Kern', count: 1 },
  ],
};

export default californiaCountiesData;
