"""Generate the small browser ephemeris from JPL DE440 and IERS Earth orientation.

Usage (Python with skyfield==1.55 and numpy installed):
  python generate-solar-ephemeris.py --data-dir /path/to/astronomy-data

The data directory must contain de440s.bsp and finals2000A.all, downloaded from:
https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de440s.bsp
https://datacenter.iers.org/data/9/finals2000A.all
This script does not download anything. Commit the generated JS with the page.
"""
import argparse
import hashlib
import json
import math
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

import numpy as np
import skyfield
from skyfield import almanac
from skyfield.api import Loader, load_file, wgs84
from skyfield.data import iers


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--references", action="store_true",
                        help="Also regenerate independent topocentric test fixtures")
    args = parser.parse_args()
    loader = Loader(str(args.data_dir))
    ts = loader.timescale(builtin=False)
    with (args.data_dir / "finals2000A.all").open("rb") as source:
        earth_orientation = iers.parse_x_y_dut1_from_finals_all(source)
    iers.install_polar_motion_table(ts, earth_orientation)
    ephemeris = load_file(str(args.data_dir / "de440s.bsp"))

    # Include September for the fall pin windows, plus padding around slider dates.
    start = datetime(2026, 8, 31, tzinfo=timezone.utc)
    end = datetime(2027, 4, 3, tzinfo=timezone.utc)
    fractions = np.array([0, 1 / 3, 2 / 3, 1])
    interpolation = np.vander(fractions, 4, increasing=True)
    rows = []
    for day in range((end - start).days):
        date = start + timedelta(days=day)
        t = ts.utc(date.year, date.month, date.day, fractions * 24)
        if t.ut1[0] - 2400000.5 < earth_orientation['utc_mjd'][0] or t.ut1[-1] - 2400000.5 > earth_orientation['utc_mjd'][-1]:
            raise ValueError("IERS data does not cover the requested season")
        position = ephemeris['earth'].at(t).observe(ephemeris['sun']).apparent()
        ra, dec, distance = position.radec(epoch='date')
        _, pole_x, pole_y = t.polar_motion_angles()
        values = np.array([
            np.degrees(np.unwrap(ra.radians)), dec.degrees, distance.km,
            np.degrees(np.unwrap(t.gast * np.pi / 12)), pole_x, pole_y,
        ])
        # Four coefficients per quantity, ascending powers of fraction of UTC day.
        coefficients = np.linalg.solve(interpolation, values.T).T.flatten()
        rows.append([float(f'{value:.14g}') for value in coefficients])

    metadata = {
        'model': 'JPL DE440 / Skyfield ' + skyfield.__version__,
        'startMs': int(start.timestamp() * 1000),
        'endMs': int(end.timestamp() * 1000),
        'stepMs': 86400000,
        'de440Sha256': hashlib.sha256((args.data_dir / 'de440s.bsp').read_bytes()).hexdigest(),
        'iersSha256': hashlib.sha256((args.data_dir / 'finals2000A.all').read_bytes()).hexdigest(),
    }
    target = Path(__file__).resolve().parent / 'solar-ephemeris.js'
    header = """/* ============================================================
   SOLAR DATA
   Generated by generate-solar-ephemeris.py from JPL DE440
   and IERS Earth-orientation data. Regenerate to change the numbers.
   ============================================================ */

// create the global GGHEphemeris object so solar-calculations.js can read this data
// this file stores data only; it does not calculate sunset or check GGH dates
// load this file before solar-calculations.js
//
// model: the astronomy model used to generate the data
// startMs: start of coverage, Aug 31, 2026 at 00:00 UTC (inclusive)
// endMs: end of coverage, Apr 3, 2027 at 00:00 UTC (noninclusive)
// both times are milliseconds since Jan 1, 1970 at 00:00 UTC
// stepMs: milliseconds between rows; 86400000 means one row per UTC day
// de440Sha256 and iersSha256: fingerprints identifying the exact source files used
//
// days: one row per day, starting on startMs
// each row has six groups of four numbers, in the following order:
//   0-3: right ascension (RA), the sun's east-west sky coordinate in degrees
//   4-7: solar declination, the sun's angle north/south of Earth's equator in degrees
//   8-11: distance from Earth's center to the sun in km
//   12-15: Greenwich apparent sidereal time (GAST), Earth's rotation angle measured relative to the equinox, in degrees
//   16-19: polar motion x, x-component of Earth's rotational-pole shift in arcseconds
//   20-23: polar motion y, y component of Earth's rotational-pole shift in arcseconds
//
// each group stores the coefficients a, b, c, d for a cubic function of the form a+bx+cx^2+dx^3, used to estimate the values of that group's desired quantity at different times in a day
// x is the fraction of the UTC day elapsed (0 at midnight, 0.5 at noon)
"""
    body = json.dumps(metadata, indent=2)[:-2] + ',\n  "days": [\n'
    body += ',\n'.join('    ' + json.dumps(row, separators=(',', ':')) for row in rows)
    body += '\n  ]\n}'
    target.write_text(header + 'globalThis.GGHEphemeris = ' + body + ';\n')
    print(f'Generated {len(rows)} days in {target.name} ({target.stat().st_size:,} bytes)')
    if args.references:
        generate_references(ts, ephemeris, target.parent)


def generate_references(ts, ephemeris, project):
    """Use full topocentric Skyfield, not the browser interpolation, as the oracle."""
    html = (project / 'index_fa26.html').read_text()
    pins = re.findall(r'\{ name: "([^"]+)", lat: ([-\d.]+), lng: ([-\d.]+)', html)
    bridge = {}
    for name in ['MIDPOINT', 'NORTH_TOWER', 'SOUTH_TOWER']:
        match = re.search(r'const ' + name + r' = \[([-\d.]+), ([-\d.]+)\]', html)
        bridge[name] = tuple(map(float, match.groups()))

    def bearing(lng, lat, target):
        lon2, lat2 = target
        phi1, phi2, dl = map(math.radians, [lat, lat2, lon2 - lng])
        y = math.sin(dl) * math.cos(phi2)
        x = math.cos(phi1) * math.sin(phi2) - math.sin(phi1) * math.cos(phi2) * math.cos(dl)
        return math.degrees(math.atan2(y, x)) % 360

    fixtures = []
    base = datetime(2026, 1, 1, tzinfo=timezone.utc)
    for name, latitude, longitude in pins:
        lat, lng = float(latitude), float(longitude)
        observer = ephemeris['earth'] + wgs84.latlon(lat, lng)
        sun = ephemeris['sun']
        t, valid = almanac.find_settings(observer, sun, ts.utc(2026, 9, 1, 12),
                                        ts.utc(2027, 4, 1, 12), horizon_degrees=-0.833)
        assert np.all(valid)
        for _ in range(3):
            altitude = observer.at(t).observe(sun).apparent().altaz()[0].degrees
            later = observer.at(ts.tt_jd(t.tt + 1 / 86400)).observe(sun).apparent().altaz()[0].degrees
            t = ts.tt_jd(t.tt - (altitude + 0.833) / (later - altitude) / 86400)
        azimuth = observer.at(t).observe(sun).apparent().altaz()[1].degrees
        days = np.array([(ti.utc_datetime() - timedelta(hours=8) - base).days + 1 for ti in t])
        center = bearing(lng, lat, bridge['MIDPOINT'])
        north = bearing(lng, lat, bridge['NORTH_TOWER'])
        south = bearing(lng, lat, bridge['SOUTH_TOWER'])
        width = abs((north - south + 180) % 360 - 180) / 3
        difference = abs((azimuth - center + 180) % 360 - 180)
        good = days[difference <= width / 2].tolist()
        samples = []
        for day, ti, angle in zip(days, t, azimuth):
            if (int(day) in good or int(day) - 1 in good or int(day) + 1 in good
                    or (int(day) - 244) % 21 == 0 or int(day) in [274, 365, 366, 455]):
                samples.append([int(day), round(ti.utc_datetime().timestamp() * 1000, 3),
                                round(float(angle), 10)])
        fixtures.append({'name': name, 'lat': lat, 'lng': lng,
                         'fall': [d for d in good if d <= 365],
                         'spring': [d for d in good if d > 365], 'samples': samples})
    destination = project / 'tests/fixtures/solar-reference.json'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps({
        'model': f'Independent topocentric Skyfield {skyfield.__version__} / DE440 / IERS, altitude -0.833 deg, height 0 m',
        'pins': fixtures
    }, indent=2) + '\n')
    print(f'Generated reference windows and sunset samples for {len(fixtures)} locations')


if __name__ == '__main__':
    main()
